# -*- coding: utf-8 -*-
"""bornhuettafergusson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fY9lK0ccChLJ_e_0xrZ89Aqrob70OsUP
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import date
import re

st.set_page_config(page_title="Chain Ladder & BF IBNR Calculator", layout="wide")

# ---------- CUSTOM CSS ----------
st.markdown("""
<style>
    /* Global font */
    .stApp {
        background-color: #FFFFFF;
        color: #000000;
        font-family: 'Calisto MT', serif;
        font-size: 11pt;
    }

    /* Headers and text */
    h1, h2, h3, p, div, span, label {
        font-family: 'Calisto MT', serif;
    }

    /* Header bar */
    .header {
        background-color: #000000;
        padding: 1rem 2rem;
        display: flex;
        align-items: center;
        justify-content: flex-end;
        border-bottom: 3px solid #D4AF37;
        margin-bottom: 2rem;
    }
    .nav-links a {
        color: #FFFFFF;
        margin-left: 2rem;
        text-decoration: none;
        font-weight: 500;
    }
    .nav-links a:hover {
        color: #D4AF37;
    }

    /* Hero section */
    .hero {
        background: linear-gradient(135deg, #000000 0%, #333333 100%);
        color: #FFFFFF;
        padding: 2rem;
        text-align: center;
        border-bottom: 3px solid #D4AF37;
        margin-bottom: 2rem;
    }
    .hero h1 {
        color: #D4AF37;
        font-size: 2.5rem;
        margin-bottom: 0.5rem;
    }
    .hero p {
        font-size: 1.2rem;
        max-width: 800px;
        margin: 0 auto;
    }

    /* Gold containers for input sections */
    .gold-container {
        background-color: #F9F9F9;
        border: 2px solid #D4AF37;
        border-radius: 10px;
        padding: 1rem;
        margin-bottom: 1.5rem;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    .gold-container h3 {
        color: #D4AF37;
        margin-top: 0;
        margin-bottom: 0.75rem;
        font-size: 1.2rem;
        font-weight: bold;
    }
    .gold-container p {
        color: #666666;
        font-size: 0.85rem;
        margin-bottom: 0.5rem;
    }

    /* Buttons */
    .stButton > button {
        background-color: #D4AF37 !important;
        color: #000000 !important;
        border: none !important;
        border-radius: 4px !important;
        font-weight: bold !important;
    }
    .stButton > button:hover {
        background-color: #B8960F !important;
        color: #FFFFFF !important;
    }

    /* File uploader styling */
    .stFileUploader {
        border: 2px dashed #D4AF37;
        border-radius: 10px;
        padding: 1rem;
        background-color: #F9F9F9;
    }

    /* Cards */
    .card {
        background-color: #F9F9F9;
        border: 1px solid #D4AF37;
        border-radius: 8px;
        padding: 1.5rem;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
    .card h3 {
        color: #D4AF37;
        border-bottom: 2px solid #D4AF37;
        padding-bottom: 0.5rem;
    }

    /* Footer */
    .footer {
        background-color: #000000;
        color: #FFFFFF;
        text-align: center;
        padding: 1.5rem;
        border-top: 3px solid #D4AF37;
        margin-top: 3rem;
    }
    .footer a {
        color: #D4AF37;
        text-decoration: none;
    }

    /* Data quality boxes */
    .data-quality-info {
        background-color: #E8F4FD;
        border-left: 5px solid #2196F3;
        padding: 15px;
        border-radius: 5px;
        margin: 10px 0;
    }

    .data-quality-warning {
        background-color: #FFF3E0;
        border-left: 5px solid #FF9800;
        padding: 15px;
        border-radius: 5px;
        margin: 10px 0;
    }

    .data-quality-error {
        background-color: #FFEBEE;
        border-left: 5px solid #F44336;
        padding: 15px;
        border-radius: 5px;
        margin: 10px 0;
    }

    .data-quality-success {
        background-color: #E8F5E9;
        border-left: 5px solid #4CAF50;
        padding: 15px;
        border-radius: 5px;
        margin: 10px 0;
    }
</style>
""", unsafe_allow_html=True)

# ---------- CORE FUNCTIONS ----------

def get_accident_period(date, start_date, period_unit):
    """Assign accident period number based on granularity"""
    if period_unit == 'M':
        months_diff = (date.year - start_date.year) * 12 + (date.month - start_date.month)
        return months_diff
    elif period_unit == 'Q':
        date_quarter = date.year * 4 + (date.month - 1) // 3
        start_quarter = start_date.year * 4 + (start_date.month - 1) // 3
        return date_quarter - start_quarter
    else:
        return date.year - start_date.year

def get_development_period(loss_date, report_date, period_unit, n_dev_periods):
    """Calculate development period (lag)"""
    if period_unit == 'M':
        lag = (report_date.year - loss_date.year) * 12 + (report_date.month - loss_date.month)
    elif period_unit == 'Q':
        report_quarter = report_date.year * 4 + (report_date.month - 1) // 3
        loss_quarter = loss_date.year * 4 + (loss_date.month - 1) // 3
        lag = report_quarter - loss_quarter
    else:
        lag = report_date.year - loss_date.year
    return max(0, min(lag, n_dev_periods - 1))

def create_incremental_triangle(data, amount_col, n_dev_periods, max_accident_period):
    """Create incremental triangle from data"""
    inc_triangle = data.pivot_table(
        index='Accident_Period',
        columns='Development_Period',
        values=amount_col,
        aggfunc='sum',
        fill_value=0
    )

    for dev in range(n_dev_periods):
        if dev not in inc_triangle.columns:
            inc_triangle[dev] = 0.0

    for ap in range(max_accident_period + 1):
        if ap not in inc_triangle.index:
            inc_triangle.loc[ap] = 0.0

    inc_triangle = inc_triangle.reindex(sorted(inc_triangle.columns), axis=1)
    inc_triangle = inc_triangle.sort_index()
    inc_triangle = inc_triangle.fillna(0.0)

    return inc_triangle

def calculate_development_factors(cum_triangle):
    """Calculate weighted average development factors"""
    n_ay, n_dev = cum_triangle.shape
    dev_factors = []

    for j in range(n_dev - 1):
        sum_next = 0.0
        sum_curr = 0.0

        for i in range(n_ay):
            if i + j + 1 < n_ay:
                curr = cum_triangle.iloc[i, j]
                nxt = cum_triangle.iloc[i, j+1]
                if curr > 0:
                    sum_next += nxt
                    sum_curr += curr

        if sum_curr > 0:
            dev_factors.append(sum_next / sum_curr)
        else:
            dev_factors.append(1.0)

    return dev_factors

def calculate_cdfs(dev_factors):
    """Convert development factors to cumulative development factors (CDF)"""
    cdfs = []
    running_product = 1.0
    for f in reversed(dev_factors):
        running_product *= f
        cdfs.insert(0, running_product)
    return cdfs

def project_ultimate(cum_triangle, dev_factors):
    """Project ultimate claims using development factors"""
    n_ay, n_dev = cum_triangle.shape
    completed = cum_triangle.copy().astype(float)

    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if i + j < n_ay:
                last_obs = j
                break

        if last_obs == -1:
            continue

        for j in range(last_obs, n_dev - 1):
            if j < len(dev_factors):
                if completed.iloc[i, j] > 0:
                    completed.iloc[i, j+1] = completed.iloc[i, j] * dev_factors[j]
                else:
                    completed.iloc[i, j+1] = 0.0

    return completed

def calculate_chain_ladder_ibnr(cum_triangle, start_date, period_unit):
    """Calculate IBNR using pure Chain Ladder method"""
    n_ay, n_dev = cum_triangle.shape

    dev_factors = calculate_development_factors(cum_triangle)
    cdfs = calculate_cdfs(dev_factors)
    completed_triangle = project_ultimate(cum_triangle, dev_factors)

    results = []
    total_ibnr = 0.0

    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if i + j < n_ay:
                last_obs = j
                break

        if last_obs == -1:
            continue

        current = cum_triangle.iloc[i, last_obs]
        ultimate = completed_triangle.iloc[i, n_dev - 1]
        ibnr = max(ultimate - current, 0)

        total_ibnr += ibnr

        # Create readable label
        if period_unit == 'Y':
            acc_label = str(start_date.year + i)
        elif period_unit == 'Q':
            base_year = start_date.year
            base_quarter = (start_date.month - 1) // 3
            total_quarters = base_year * 4 + base_quarter + i
            year = total_quarters // 4
            quarter = total_quarters % 4 + 1
            acc_label = f"{year}-Q{quarter}"
        else:
            total_months = start_date.year * 12 + start_date.month + i
            year = (total_months - 1) // 12
            month = (total_months - 1) % 12 + 1
            acc_label = f"{year}-{month:02d}"

        results.append({
            'Accident_Period': i,
            'Accident_Period_Label': acc_label,
            'Current_Claims': current,
            'CL_Ultimate': ultimate,
            'CL_IBNR': ibnr
        })

    return {
        'results_df': pd.DataFrame(results),
        'total_ibnr': total_ibnr,
        'completed_triangle': completed_triangle,
        'dev_factors': dev_factors,
        'cdfs': cdfs
    }

def calculate_bf_ibnr(cum_triangle, dev_factors, premiums, elr, start_date, period_unit):
    """
    Calculate IBNR using Bornhuetter-Ferguson method

    Parameters:
    - cum_triangle: Cumulative claims triangle
    - dev_factors: Development factors from Chain Ladder
    - premiums: Array of premiums per accident period (length = n_ay)
    - elr: Expected Loss Ratio (0 to 1)
    """
    n_ay, n_dev = cum_triangle.shape

    # Calculate CDFs
    cdfs = calculate_cdfs(dev_factors)

    # Calculate % unreported per development period
    pct_unreported = [1 - (1/cdf) if cdf > 0 else 0 for cdf in cdfs]

    results = []
    total_bf_ibnr = 0.0

    for i in range(n_ay):
        # Find last observed development period
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if i + j < n_ay:
                last_obs = j
                break

        if last_obs == -1:
            continue

        current = cum_triangle.iloc[i, last_obs]

        # Expected ultimate = premium * ELR
        expected_ultimate = premiums[i] * elr

        # BF IBNR = Expected Ultimate * % Unreported at last_obs
        if last_obs < len(pct_unreported):
            pct_unrep = pct_unreported[last_obs]
        else:
            pct_unrep = 0

        bf_ibnr = expected_ultimate * pct_unrep
        bf_ultimate = current + bf_ibnr

        # % developed
        pct_developed = (1 - pct_unrep) * 100

        total_bf_ibnr += bf_ibnr

        # Create readable label
        if period_unit == 'Y':
            acc_label = str(start_date.year + i)
        elif period_unit == 'Q':
            base_year = start_date.year
            base_quarter = (start_date.month - 1) // 3
            total_quarters = base_year * 4 + base_quarter + i
            year = total_quarters // 4
            quarter = total_quarters % 4 + 1
            acc_label = f"{year}-Q{quarter}"
        else:
            total_months = start_date.year * 12 + start_date.month + i
            year = (total_months - 1) // 12
            month = (total_months - 1) % 12 + 1
            acc_label = f"{year}-{month:02d}"

        results.append({
            'Accident_Period': i,
            'Accident_Period_Label': acc_label,
            'Current_Claims': current,
            'Premium': premiums[i],
            'ELR': elr,
            'Expected_Ultimate': expected_ultimate,
            'Pct_Developed': pct_developed,
            'CDF_to_Ultimate': cdfs[last_obs] if last_obs < len(cdfs) else 1.0,
            'BF_IBNR': bf_ibnr,
            'BF_Ultimate': bf_ultimate
        })

    return {
        'results_df': pd.DataFrame(results),
        'total_bf_ibnr': total_bf_ibnr,
        'cdfs': cdfs,
        'pct_unreported': pct_unreported
    }

# ---------- Header ----------
st.markdown("""
<div class="header">
    <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">Services</a>
        <a href="#">Tools</a>
        <a href="#">Contact</a>
    </div>
</div>
""", unsafe_allow_html=True)

# ---------- Hero ----------
st.markdown("""
<div class="hero">
    <h1>Chain Ladder & Bornhuetter-Ferguson IBNR Calculator</h1>
    <p>Upload your claims data. Map the columns, configure BF parameters, and calculate IBNR using both Chain Ladder and Bornhuetter-Ferguson methods.</p>
</div>
""", unsafe_allow_html=True)

# ---------- Main Content ----------

# Client name input
st.markdown("""
<div class="gold-container">
    <h3>Client Information</h3>
    <p>Enter a client name for file tracking</p>
</div>
""", unsafe_allow_html=True)
client_name = st.text_input("Client Name", value="Client", label_visibility="collapsed").strip()

# IBNR Period Selection
st.markdown("""
<div class="gold-container">
    <h3>IBNR Period</h3>
    <p>Select the date range for claims to be included in the analysis</p>
</div>
""", unsafe_allow_html=True)

col1, col2 = st.columns(2)
with col1:
    from_date = st.date_input("From Date", value=date(2020, 1, 1), label_visibility="collapsed")
    st.caption("Start of period (Accident Date)")
with col2:
    to_date = st.date_input("To Date", value=date(2024, 12, 31), label_visibility="collapsed")
    st.caption("End of period (Accident Date)")

from_date = pd.to_datetime(from_date)
to_date = pd.to_datetime(to_date)

st.info(f"**Selected Period:** {from_date.date()} to {to_date.date()}")

# Granularity Selection
st.markdown("""
<div class="gold-container">
    <h3>Triangle Granularity</h3>
    <p>Select the granularity for the claims development triangle</p>
</div>
""", unsafe_allow_html=True)

granularity = st.selectbox(
    "Granularity",
    ["Yearly", "Quarterly", "Monthly"],
    index=0,
    label_visibility="collapsed"
)

if granularity == "Monthly":
    period_unit = 'M'
    period_name = 'Monthly'
elif granularity == "Quarterly":
    period_unit = 'Q'
    period_name = 'Quarterly'
else:
    period_unit = 'Y'
    period_name = 'Yearly'

st.caption(f"Selected: **{period_name}**")

# File uploader
st.markdown("""
<div class="gold-container">
    <h3>Upload Claims Data File</h3>
    <p>Upload your claims data (CSV or Excel format). Must contain Loss_Date and Report_Date columns.</p>
</div>
""", unsafe_allow_html=True)

uploaded_file = st.file_uploader("Choose a file", type=["csv", "xlsx", "xls"], label_visibility="collapsed")

if uploaded_file is not None:
    try:
        original_filename = uploaded_file.name
        base_filename = re.sub(r'\.[^.]*$', '', original_filename)

        # Read file
        ext = uploaded_file.name.split('.')[-1].lower()
        if ext == 'csv':
            try:
                df = pd.read_csv(uploaded_file, encoding='utf-8')
            except:
                uploaded_file.seek(0)
                df = pd.read_csv(uploaded_file, encoding='cp1252')
        else:
            df = pd.read_excel(uploaded_file)

        # Clean up unnamed columns
        unnamed = [c for c in df.columns if 'Unnamed' in c]
        if unnamed:
            df = df.drop(columns=unnamed)

        st.write("### Preview of your data")
        st.dataframe(df.head())

        # Column selection
        st.write("### Map Your Columns")
        all_cols = df.columns.tolist()

        col1, col2 = st.columns(2)
        with col1:
            loss_date_col = st.selectbox("Loss Date column", ["Select..."] + all_cols)
        with col2:
            report_date_col = st.selectbox("Report Date column", ["Select..."] + all_cols)

        if loss_date_col == "Select..." or report_date_col == "Select...":
            st.warning("Please select both date columns to continue.")
            st.stop()

        # Grouping columns (optional)
        grouping_cols = st.multiselect(
            "Grouping columns (optional, e.g., Line of Business)",
            [c for c in all_cols if c not in [loss_date_col, report_date_col]]
        )

        # Numeric columns for amounts
        num_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
        amount_candidates = [c for c in num_cols if c not in [loss_date_col, report_date_col] and 'date' not in c.lower()]

        if not amount_candidates:
            st.error("No numeric columns found for claim amounts.")
            st.stop()

        amount_cols = st.multiselect("Select claim amount columns", amount_candidates)

        if not amount_cols:
            st.warning("Please select at least one amount column.")
            st.stop()

        # ====================================================================
        # BF METHOD PARAMETERS
        # ====================================================================

        st.markdown("""
        <div class="gold-container">
            <h3>Bornhuetter-Ferguson Parameters</h3>
            <p>Configure the BF method inputs - Premiums and Expected Loss Ratio</p>
        </div>
        """, unsafe_allow_html=True)

        enable_bf = st.checkbox("Enable Bornhuetter-Ferguson Calculation", value=True)

        if enable_bf:
            # ELR Input
            col1, col2 = st.columns(2)
            with col1:
                elr_input = st.number_input(
                    "Expected Loss Ratio (ELR) %",
                    min_value=0.0,
                    max_value=200.0,
                    value=70.0,
                    step=1.0
                ) / 100
                st.caption(f"A-priori loss ratio: **{elr_input*100:.1f}%**")

            with col2:
                premium_input_method = st.radio(
                    "Premium Input Method",
                    ["Manual Entry", "Upload Premium File"],
                    horizontal=True
                )

            if premium_input_method == "Manual Entry":
                st.markdown("""
                <div class="gold-container">
                    <h3>Manual Premium Entry</h3>
                    <p>Enter the earned premium for each accident period. The number of periods will be determined after data processing.</p>
                </div>
                """, unsafe_allow_html=True)

                # We'll collect premiums after we know n_accident_periods
                premiums_dict = {}
                premium_input_placeholder = st.empty()

            else:
                st.markdown("""
                <div class="gold-container">
                    <h3>Upload Premium Data</h3>
                    <p>Upload a CSV/Excel file with premiums. Must have columns matching the accident periods.</p>
                </div>
                """, unsafe_allow_html=True)

                premium_file = st.file_uploader(
                    "Upload Premium File",
                    type=["csv", "xlsx", "xls"],
                    key="premium_upload"
                )

        # ====================================================================
        # DATA QUALITY CHECKS
        # ====================================================================

        st.write("### Data Quality Checks")

        # Convert dates
        try:
            df[loss_date_col] = pd.to_datetime(df[loss_date_col], errors='coerce')
            df[report_date_col] = pd.to_datetime(df[report_date_col], errors='coerce')

            invalid_dates = df[loss_date_col].isna().sum() + df[report_date_col].isna().sum()
            if invalid_dates > 0:
                st.markdown(f'<div class="data-quality-error">❌ {invalid_dates} invalid dates found. Please check format (YYYY-MM-DD) and re-upload.</div>', unsafe_allow_html=True)
                st.stop()
            else:
                st.markdown(f'<div class="data-quality-success">✅ All dates parsed successfully</div>', unsafe_allow_html=True)
        except Exception as e:
            st.markdown(f'<div class="data-quality-error">❌ Date conversion error: {e}</div>', unsafe_allow_html=True)
            st.stop()

        # Drop invalid dates
        df = df.dropna(subset=[loss_date_col, report_date_col])

        # Check date reasonability
        future_loss = (df[loss_date_col] > pd.Timestamp.now()).sum()
        future_report = (df[report_date_col] > pd.Timestamp.now()).sum()
        report_before_loss = (df[report_date_col] < df[loss_date_col]).sum()

        if future_loss > 0:
            st.markdown(f'<div class="data-quality-warning">⚠️ {future_loss} rows have Loss_Date in the future</div>', unsafe_allow_html=True)
        if future_report > 0:
            st.markdown(f'<div class="data-quality-warning">⚠️ {future_report} rows have Report_Date in the future</div>', unsafe_allow_html=True)
        if report_before_loss > 0:
            st.markdown(f'<div class="data-quality-error">❌ {report_before_loss} rows have Report_Date before Loss_Date - these will be excluded</div>', unsafe_allow_html=True)
            df = df[df[report_date_col] >= df[loss_date_col]]

        # Check for missing values in amount columns
        for col in amount_cols:
            missing = df[col].isna().sum()
            if missing > 0:
                st.markdown(f'<div class="data-quality-warning">⚠️ Column "{col}" has {missing} missing values. Rows with missing amounts will be excluded.</div>', unsafe_allow_html=True)

        # Check for negative values
        for col in amount_cols:
            negative = (df[col] < 0).sum()
            if negative > 0:
                st.markdown(f'<div class="data-quality-warning">⚠️ Column "{col}" has {negative} negative values.</div>', unsafe_allow_html=True)

        # Remove duplicates
        dup_count = df.duplicated().sum()
        if dup_count > 0:
            df = df.drop_duplicates()
            st.markdown(f'<div class="data-quality-info">ℹ️ Removed {dup_count} duplicate rows.</div>', unsafe_allow_html=True)
        else:
            st.markdown(f'<div class="data-quality-success">✅ No duplicate rows found</div>', unsafe_allow_html=True)

        # Filter by date range
        mask = (df[loss_date_col] >= from_date) & (df[loss_date_col] <= to_date)
        df_filtered = df[mask].copy()

        if df_filtered.empty:
            st.markdown(f'<div class="data-quality-error">❌ No data found for period {from_date.date()} to {to_date.date()}</div>', unsafe_allow_html=True)
            st.stop()

        records_excluded = len(df) - len(df_filtered)
        st.markdown(f'<div class="data-quality-success">✅ {len(df_filtered)} records in selected period ({records_excluded} excluded)</div>', unsafe_allow_html=True)

        # ====================================================================
        # CALCULATE TRIANGLE PARAMETERS
        # ====================================================================

        if period_unit == 'M':
            total_months = (to_date.year - from_date.year) * 12 + (to_date.month - from_date.month)
            n_dev_periods = total_months + 1
        elif period_unit == 'Q':
            start_quarter = from_date.year * 4 + (from_date.month - 1) // 3
            end_quarter = to_date.year * 4 + (to_date.month - 1) // 3
            total_quarters = end_quarter - start_quarter
            n_dev_periods = total_quarters + 1
        else:
            total_years = to_date.year - from_date.year
            n_dev_periods = total_years + 1

        # Create accident and development periods
        df_filtered['Accident_Period'] = df_filtered[loss_date_col].apply(
            lambda x: get_accident_period(x, from_date, period_unit)
        )
        df_filtered['Development_Period'] = df_filtered.apply(
            lambda row: get_development_period(row[loss_date_col], row[report_date_col], period_unit, n_dev_periods),
            axis=1
        )

        accident_periods = sorted(df_filtered['Accident_Period'].unique())
        max_accident_period = max(accident_periods)
        n_accident_periods = max_accident_period + 1

        st.write(f"### Triangle Configuration")
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Granularity", period_name)
        with col2:
            st.metric("Development Periods", n_dev_periods)
        with col3:
            st.metric("Accident Periods", n_accident_periods)

        # ====================================================================
        # BF PREMIUM INPUT (now we know n_accident_periods)
        # ====================================================================

        premiums = None
        premium_data_valid = True

        if enable_bf:
            if premium_input_method == "Manual Entry":
                st.write("### Enter Premiums per Accident Period")
                st.caption(f"Enter earned premium for each of the {n_accident_periods} accident periods")

                premiums = []
                # Create columns for premium entry (max 6 per row)
                n_cols = min(6, n_accident_periods)
                for row_start in range(0, n_accident_periods, n_cols):
                    cols = st.columns(n_cols)
                    for col_idx in range(n_cols):
                        ap_idx = row_start + col_idx
                        if ap_idx < n_accident_periods:
                            with cols[col_idx]:
                                # Generate label
                                if period_unit == 'Y':
                                    label = str(from_date.year + ap_idx)
                                elif period_unit == 'Q':
                                    base_year = from_date.year
                                    base_quarter = (from_date.month - 1) // 3
                                    total_quarters = base_year * 4 + base_quarter + ap_idx
                                    year = total_quarters // 4
                                    quarter = total_quarters % 4 + 1
                                    label = f"{year}-Q{quarter}"
                                else:
                                    total_months = from_date.year * 12 + from_date.month + ap_idx
                                    year = (total_months - 1) // 12
                                    month = (total_months - 1) % 12 + 1
                                    label = f"{year}-{month:02d}"

                                prem = st.number_input(
                                    f"AP {ap_idx} ({label})",
                                    min_value=0.0,
                                    value=1000000.0,
                                    step=100000.0,
                                    format="%.0f",
                                    key=f"premium_{ap_idx}"
                                )
                                premiums.append(prem)

                # Validate premiums
                if len(premiums) != n_accident_periods:
                    st.markdown(f'<div class="data-quality-error">❌ Number of premiums ({len(premiums)}) does not match number of accident periods ({n_accident_periods})</div>', unsafe_allow_html=True)
                    premium_data_valid = False

                # Check for zero or negative premiums
                if premium_data_valid:
                    zero_prems = sum(1 for p in premiums if p <= 0)
                    if zero_prems > 0:
                        st.markdown(f'<div class="data-quality-warning">⚠️ {zero_prems} accident periods have zero or negative premiums</div>', unsafe_allow_html=True)

            else:  # Upload Premium File
                if premium_file is not None:
                    try:
                        # Read premium file
                        prem_ext = premium_file.name.split('.')[-1].lower()
                        if prem_ext == 'csv':
                            prem_df = pd.read_csv(premium_file)
                        else:
                            prem_df = pd.read_excel(premium_file)

                        st.write("### Premium Data Preview")
                        st.dataframe(prem_df.head())

                        # Let user select premium column
                        prem_cols = prem_df.columns.tolist()

                        # Try to auto-detect premium column
                        premium_amount_col = st.selectbox(
                            "Select Premium Amount Column",
                            prem_cols,
                            index=0 if prem_cols else 0
                        )

                        # Check if number of rows matches
                        if len(prem_df) != n_accident_periods:
                            st.markdown(f'<div class="data-quality-error">❌ Premium file has {len(prem_df)} rows but need {n_accident_periods} accident periods</div>', unsafe_allow_html=True)
                            premium_data_valid = False
                        else:
                            premiums = prem_df[premium_amount_col].tolist()

                            # Validate premiums
                            missing_prems = sum(1 for p in premiums if pd.isna(p))
                            if missing_prems > 0:
                                st.markdown(f'<div class="data-quality-error">❌ {missing_prems} missing premium values found</div>', unsafe_allow_html=True)
                                premium_data_valid = False
                            else:
                                zero_prems = sum(1 for p in premiums if p <= 0)
                                if zero_prems > 0:
                                    st.markdown(f'<div class="data-quality-warning">⚠️ {zero_prems} accident periods have zero or negative premiums</div>', unsafe_allow_html=True)

                                st.markdown(f'<div class="data-quality-success">✅ Premium data loaded successfully ({len(premiums)} periods)</div>', unsafe_allow_html=True)

                    except Exception as e:
                        st.markdown(f'<div class="data-quality-error">❌ Error reading premium file: {e}</div>', unsafe_allow_html=True)
                        premium_data_valid = False
                else:
                    st.warning("Please upload a premium file to use BF method")
                    premium_data_valid = False

        # ====================================================================
        # RUN CALCULATIONS
        # ====================================================================

        # Get group combinations
        if grouping_cols:
            group_combinations = df_filtered[grouping_cols].drop_duplicates()
        else:
            group_combinations = pd.DataFrame([{'All Data': 'All'}])

        all_cl_results = []
        all_bf_results = []
        all_incremental_triangles = {}
        all_dev_factors = {}
        all_cdfs = {}
        all_bf_details = {}

        with st.spinner("Calculating IBNR..."):
            for idx, group_row in group_combinations.iterrows():
                # Filter data for this group
                group_mask = pd.Series(True, index=df_filtered.index)
                group_name_parts = []

                for col in grouping_cols:
                    group_mask = group_mask & (df_filtered[col] == group_row[col])
                    group_name_parts.append(f"{group_row[col]}")

                group_name = " | ".join(group_name_parts) if group_name_parts else "All Data"
                group_data = df_filtered[group_mask].copy()

                if len(group_data) == 0:
                    continue

                for amount_col in amount_cols:
                    valid_data = group_data.dropna(subset=[amount_col])

                    if len(valid_data) == 0:
                        continue

                    # Create incremental triangle
                    inc_triangle = create_incremental_triangle(valid_data, amount_col, n_dev_periods, max_accident_period)
                    cum_triangle = inc_triangle.cumsum(axis=1)

                    triangle_key = f"{group_name} | {amount_col}"
                    all_incremental_triangles[triangle_key] = inc_triangle

                    # Run Chain Ladder
                    cl_result = calculate_chain_ladder_ibnr(cum_triangle, from_date, period_unit)

                    all_dev_factors[triangle_key] = cl_result['dev_factors']
                    all_cdfs[triangle_key] = cl_result['cdfs']

                    # Add grouping info to CL results
                    cl_df = cl_result['results_df'].copy()
                    if grouping_cols:
                        for col in grouping_cols:
                            cl_df[col] = group_row[col]
                    cl_df['Amount_Column'] = amount_col
                    cl_df['Method'] = 'Chain Ladder'

                    all_cl_results.append(cl_df)

                    # Run BF if enabled and premiums available
                    if enable_bf and premium_data_valid and premiums is not None:
                        bf_result = calculate_bf_ibnr(
                            cum_triangle,
                            cl_result['dev_factors'],
                            premiums,
                            elr_input,
                            from_date,
                            period_unit
                        )

                        bf_df = bf_result['results_df'].copy()
                        if grouping_cols:
                            for col in grouping_cols:
                                bf_df[col] = group_row[col]
                        bf_df['Amount_Column'] = amount_col
                        bf_df['Method'] = 'Bornhuetter-Ferguson'

                        all_bf_results.append(bf_df)
                        all_bf_details[triangle_key] = bf_result

        # ====================================================================
        # DISPLAY RESULTS
        # ====================================================================

        st.write("## 📊 IBNR Results")

        if all_cl_results:
            # Combine CL results
            cl_combined = pd.concat(all_cl_results, ignore_index=True)

            # Create CL summary
            if grouping_cols:
                cl_summary_cols = grouping_cols + ['Amount_Column']
            else:
                cl_summary_cols = ['Amount_Column']

            cl_summary = cl_combined.groupby(cl_summary_cols).agg({
                'Current_Claims': 'sum',
                'CL_Ultimate': 'sum',
                'CL_IBNR': 'sum'
            }).reset_index()

            cl_summary['CL_IBNR_Ratio'] = cl_summary['CL_IBNR'] / cl_summary['CL_Ultimate']
            cl_summary['CL_IBNR_Ratio'] = cl_summary['CL_IBNR_Ratio'].fillna(0)

            # If BF results exist, merge them
            if all_bf_results:
                bf_combined = pd.concat(all_bf_results, ignore_index=True)

                bf_summary = bf_combined.groupby(cl_summary_cols).agg({
                    'Current_Claims': 'sum',
                    'Expected_Ultimate': 'sum',
                    'BF_IBNR': 'sum',
                    'BF_Ultimate': 'sum',
                    'Premium': 'sum'
                }).reset_index()

                bf_summary['BF_IBNR_Ratio'] = bf_summary['BF_IBNR'] / bf_summary['BF_Ultimate']
                bf_summary['BF_IBNR_Ratio'] = bf_summary['BF_IBNR_Ratio'].fillna(0)

                # Merge CL and BF summaries
                combined_summary = cl_summary.merge(bf_summary, on=cl_summary_cols, how='outer')
                combined_summary = combined_summary.fillna(0)
            else:
                combined_summary = cl_summary.copy()
                combined_summary['ELR_Used'] = elr_input if enable_bf else 'N/A'

            # Add TOTAL row
            total_row = {}
            if grouping_cols:
                for col in grouping_cols:
                    total_row[col] = "TOTAL"
            else:
                total_row['Amount_Column'] = "TOTAL"

            total_row['Current_Claims'] = combined_summary['Current_Claims'].sum()
            total_row['CL_Ultimate'] = combined_summary['CL_Ultimate'].sum()
            total_row['CL_IBNR'] = combined_summary['CL_IBNR'].sum()
            total_row['CL_IBNR_Ratio'] = total_row['CL_IBNR'] / total_row['CL_Ultimate'] if total_row['CL_Ultimate'] > 0 else 0

            if all_bf_results:
                total_row['Premium'] = combined_summary['Premium'].sum()
                total_row['Expected_Ultimate'] = combined_summary['Expected_Ultimate'].sum()
                total_row['BF_IBNR'] = combined_summary['BF_IBNR'].sum()
                total_row['BF_Ultimate'] = combined_summary['BF_Ultimate'].sum()
                total_row['BF_IBNR_Ratio'] = total_row['BF_IBNR'] / total_row['BF_Ultimate'] if total_row['BF_Ultimate'] > 0 else 0

            combined_summary = pd.concat([combined_summary, pd.DataFrame([total_row])], ignore_index=True)

            # Display Summary
            st.subheader("IBNR Summary - Chain Ladder vs Bornhuetter-Ferguson")

            display_summary = combined_summary.copy()
            for col in display_summary.columns:
                if col not in (grouping_cols + ['Amount_Column'] if grouping_cols else ['Amount_Column']):
                    if 'Ratio' in col:
                        display_summary[col] = display_summary[col].apply(lambda x: f"{x:.2%}" if isinstance(x, (int, float)) else x)
                    elif 'ELR' in col:
                        display_summary[col] = display_summary[col].apply(lambda x: f"{x:.1%}" if isinstance(x, (int, float)) else x)
                    else:
                        display_summary[col] = display_summary[col].apply(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)

            st.dataframe(display_summary, use_container_width=True)

            # Display BF Parameters if used
            if enable_bf and premium_data_valid:
                st.subheader("BF Parameters Used")
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Expected Loss Ratio", f"{elr_input*100:.1f}%")
                with col2:
                    st.metric("Total Premium", f"{sum(premiums):,.0f}")
                with col3:
                    st.metric("Expected Ultimate (All Years)", f"{sum(premiums) * elr_input:,.0f}")

            # Display Development Factors
            if all_dev_factors:
                with st.expander("📈 Development Factors & CDFs"):
                    for key, factors in all_dev_factors.items():
                        st.write(f"**{key}**")
                        col1, col2 = st.columns(2)
                        with col1:
                            st.write("Development Factors:")
                            st.write([round(x, 4) for x in factors])
                        with col2:
                            if key in all_cdfs:
                                st.write("CDFs to Ultimate:")
                                st.write([round(x, 4) for x in all_cdfs[key]])
                        if key in all_bf_details:
                            st.write("BF % Unreported:")
                            pct_unrep = all_bf_details[key].get('pct_unreported', [])
                            st.write([f"{x*100:.1f}%" for x in pct_unrep])
                        st.write("---")

            # Display Detailed IBNR by Accident Period
            with st.expander("📋 Detailed IBNR by Accident Period"):
                for key in all_incremental_triangles.keys():
                    st.write(f"**{key}**")

                    # Get CL results for this key
                    group_val = key.split(' | ')[0]
                    amount_val = key.split(' | ')[-1]

                    cl_detail = cl_combined[
                        (cl_combined['Amount_Column'] == amount_val)
                    ]
                    if grouping_cols:
                        for col in grouping_cols:
                            if group_val != 'All Data':
                                cl_detail = cl_detail[cl_detail[col] == group_val]

                    if len(cl_detail) > 0:
                        if all_bf_results:
                            # Merge CL and BF details
                            bf_detail = bf_combined[
                                (bf_combined['Amount_Column'] == amount_val)
                            ]
                            if grouping_cols:
                                for col in grouping_cols:
                                    if group_val != 'All Data':
                                        bf_detail = bf_detail[bf_detail[col] == group_val]

                            # Combine
                            detail_cols = ['Accident_Period_Label', 'Current_Claims',
                                          'CL_IBNR', 'CL_Ultimate',
                                          'Premium', 'Expected_Ultimate',
                                          'Pct_Developed', 'BF_IBNR', 'BF_Ultimate']

                            merged_detail = cl_detail[['Accident_Period_Label', 'Current_Claims', 'CL_IBNR', 'CL_Ultimate']].merge(
                                bf_detail[['Accident_Period_Label', 'Premium', 'Expected_Ultimate', 'Pct_Developed', 'BF_IBNR', 'BF_Ultimate']],
                                on='Accident_Period_Label',
                                how='left'
                            ).fillna(0)

                            display_detail = merged_detail.copy()
                        else:
                            detail_cols = ['Accident_Period_Label', 'Current_Claims', 'CL_IBNR', 'CL_Ultimate']
                            display_detail = cl_detail[detail_cols].copy()

                        # Format numbers
                        for col in display_detail.columns:
                            if col != 'Accident_Period_Label':
                                if 'Pct_' in col:
                                    display_detail[col] = display_detail[col].apply(lambda x: f"{x:.1f}%" if isinstance(x, (int, float)) else x)
                                else:
                                    display_detail[col] = display_detail[col].apply(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)

                        st.dataframe(display_detail, use_container_width=True)
                    st.write("---")

            # ====================================================================
            # DOWNLOAD EXCEL
            # ====================================================================

            st.write("### 📥 Download Results")
            output = BytesIO()

            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                # Combined Summary
                combined_summary.to_excel(writer, index=False, sheet_name='IBNR_Summary')

                # CL Detailed
                cl_combined.to_excel(writer, index=False, sheet_name='CL_IBNR_Detail')

                # BF Detailed (if available)
                if all_bf_results:
                    bf_combined.to_excel(writer, index=False, sheet_name='BF_IBNR_Detail')

                # Development Factors
                dev_factors_df = pd.DataFrame()
                for key, factors in all_dev_factors.items():
                    temp_df = pd.DataFrame({
                        'Group_Amount': key,
                        'Development_Period': range(len(factors)),
                        'Development_Factor': factors
                    })
                    dev_factors_df = pd.concat([dev_factors_df, temp_df], ignore_index=True)
                dev_factors_df.to_excel(writer, index=False, sheet_name='Development_Factors')

                # CDFs
                cdfs_df = pd.DataFrame()
                for key, cdfs in all_cdfs.items():
                    temp_df = pd.DataFrame({
                        'Group_Amount': key,
                        'Development_Period': range(len(cdfs)),
                        'CDF_to_Ultimate': cdfs
                    })
                    cdfs_df = pd.concat([cdfs_df, temp_df], ignore_index=True)
                cdfs_df.to_excel(writer, index=False, sheet_name='CDFs_to_Ultimate')

                # Incremental Triangles
                inc_combined = pd.DataFrame()
                for key, inc_triangle in all_incremental_triangles.items():
                    temp = inc_triangle.copy()
                    temp['Group_Amount'] = key
                    inc_combined = pd.concat([inc_combined, temp])
                inc_combined.to_excel(writer, sheet_name='Incremental_Triangles')

                # Parameters
                params_dict = {
                    'Parameter': ['Start Date', 'End Date', 'Granularity', 'Dev Periods', 'Grouping Columns', 'Amount Columns'],
                    'Value': [
                        str(from_date.date()),
                        str(to_date.date()),
                        period_name,
                        n_dev_periods,
                        ', '.join(grouping_cols) if grouping_cols else 'None',
                        ', '.join(amount_cols)
                    ]
                }
                if enable_bf:
                    params_dict['Parameter'].extend(['BF Method', 'ELR', 'Premium Input'])
                    params_dict['Value'].extend([
                        'Bornhuetter-Ferguson',
                        f'{elr_input*100:.1f}%',
                        premium_input_method
                    ])

                params_df = pd.DataFrame(params_dict)
                params_df.to_excel(writer, index=False, sheet_name='Parameters')

            safe_client = re.sub(r'[\\/*?:"<>|]', "", client_name).strip() or "Client"
            safe_original = re.sub(r'[\\/*?:"<>|]', "", base_filename).strip() or "Data"
            filename = f"{safe_client}_{safe_original}_CL_BF_IBNR.xlsx"

            st.download_button(
                "📥 Download Complete IBNR Results (Excel)",
                data=output.getvalue(),
                file_name=filename,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

        else:
            st.warning("No results generated. Please check your data.")

    except Exception as e:
        st.error(f"Error processing file: {str(e)}")
        st.exception(e)

# ---------- Footer ----------
st.markdown("""
<div class="footer">
    <p>© 2026 African Actuarial Consultants. All rights reserved.</p>
</div>
""", unsafe_allow_html=True)